# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
# standalone_tags:
#   [
#     {id: 0, size: 0.162}
#   ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
# tag_bundles:
#   [
#   ]

# tag_bundles:
#   [
#     {
#       name: 'my_bundle_eight',
#       layout:
#         [
#           {id: 1, size: 0.11, x: 0.0000,  y: 0.0000,  z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 2, size: 0.11, x: 0.1380,  y: 0.0000,  z: 0.1380, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 0, size: 0.11, x: -0.0000, y: 0.0000,  z: 0.1380, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 3, size: 0.11, x: 0.1380,  y: 0.0000,  z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 5, size: 0.11, x: -0.4320, y: -0.0000, z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 4, size: 0.11, x: -0.4320, y: 0.0000,  z: 0.1380, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 6, size: 0.11, x: -0.2930, y: 0.0000,  z: 0.1380, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
#           {id: 7, size: 0.11, x: -0.2930, y: -0.0000, z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000}
#         ]
#     }
#   ]

tag_bundles:
  [
    {
      name: 'my_bundle_eight',
      layout:
        [
          {id: 1, size: 0.158, x: 0.0000,  y: 0.0000,  z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 2, size: 0.158, x: 0.1980,  y: 0.0000,  z: 0.1985, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 0, size: 0.158, x: -0.0000, y: 0.0000,  z: 0.1985, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 3, size: 0.158, x: 0.1980,  y: 0.0000,  z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 5, size: 0.158, x: -0.4900, y: -0.0000, z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 4, size: 0.158, x: -0.4900, y: 0.0000,  z: 0.1985, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 6, size: 0.158, x: -0.2920, y: 0.0000,  z: 0.1985, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000},
          {id: 7, size: 0.158, x: -0.2920, y: -0.0000, z: 0.0000, qw: 0.707, qx: -0.707, qy: 0.0000, qz: 0.0000}
        ]
    }
  ]